services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  localstack:
    ports:
      - "4566:4566"

  hmpps-auth:
    ports:
      - "9090:9090"

  aap-api:
    ports:
      - "8081:8080"
