services:
  api:
    image: ghcr.io/ministryofjustice/hmpps-arns-assessment-platform-api:local
    build:
      target: development
    command: gradle --parallel --build-cache --configuration-cache --info bootRun
    volumes:
      - ./.git:/app/.git
      - ./.gradle:/home/gradle/.gradle
      - ./build:/app/build
      - ./src:/app/src
      - ./build.gradle.kts:/app/build.gradle.kts
      - ./settings.gradle.kts:/app/settings.gradle.kts
    ports:
      - "8080:8080"
      - "5005:5005"

  typescript-client-builder:
    build: typescript-client
    depends_on:
      - api
    networks:
      - hmpps
    environment:
      - SPEC_URL=http://api:8080/v3/api-docs
      - HOST_DIR=typescript-client
    volumes:
      - ./typescript-client/.cache:/app/.cache
      - ./typescript-client/src:/app/src

volumes:
  .gradle:
  build:
