# `docker-compose.base.yml` defines common configuration shared across all deployment states.
# Other compose files (local) extend or override these settings as needed.

services:
  aap-api:
    build:
      context: ../
    networks:
      - hmpps
    ports:
      - '8081:8080'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
      interval: 5s
      retries: 100
    environment:
      - SERVER_PORT=8080
      - HMPPS_AUTH_URL=http://hmpps-auth:9090/auth
      - SPRING_PROFILES_ACTIVE=dev,postgres
      - DATABASE_ENDPOINT=postgres:5432
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - HMPPS_SQS_PROVIDER=localstack
      - HMPPS_SQS_LOCALSTACK_URL=http://localstack:4566
      - HMPPS_SQS_QUEUES_AUDIT_QUEUE_NAME=audit-queue
    depends_on:
      - postgres
      - redis
      - hmpps-auth
      - localstack

  postgres:
    image: postgres:16
    restart: always
    networks:
      - hmpps
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  redis:
    image: redis:8.6
    networks:
      - hmpps
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 20

  hmpps-auth:
    image: ghcr.io/ministryofjustice/hmpps-auth:2026-01-19.282.b6537e8
    networks:
      - hmpps
    ports:
      - '9090:9090'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/auth/health" ]
      interval: 5s
      retries: 60
    volumes:
      - ./auth_db:/auth_db
    environment:
      SERVER_PORT: 9090
      SPRING_PROFILES_ACTIVE: dev
      APPLICATION_AUTHENTICATION_UI_ALLOWLIST: 0.0.0.0/0
      SPRING_FLYWAY_LOCATIONS: classpath:db/auth,db/auth_{vendor},db/dev/data/auth_{vendor},db/dev/data/auth,filesystem:/auth_db

  localstack:
    image: localstack/localstack:4
    networks:
      - hmpps
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sqs
      - LOCALSTACK_HOST=localstack:4566
      - DEBUG=1
      - DEFAULT_REGION=eu-west-2
      - AWS_DEFAULT_REGION=eu-west-2
      - USE_SSL=false
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - './scripts/localstack/init:/etc/localstack/init/ready.d'
      - './scripts/localstack/wait:/scripts/wait'
    healthcheck:
      test: [ "CMD", "bash", "/scripts/wait/healthcheck.sh" ]
      interval: 5s
      timeout: 10s
      retries: 50

networks:
  hmpps:
