CREATE TABLE assessment_draft
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    assessment_uuid        UUID                                              NOT NULL,
    owner_user_details_uuid UUID                                             NOT NULL,
    draft_key              TEXT                                              NOT NULL,
    form_version           TEXT                                              NOT NULL,
    base_aggregate_uuid    UUID                                              NOT NULL,
    base_aggregate_version BIGINT                                            NOT NULL,
    revision               BIGINT                                            NOT NULL,
    data                   JSONB                                             NOT NULL,
    created_at             TIMESTAMPTZ                                       NOT NULL,
    updated_at             TIMESTAMPTZ                                       NOT NULL,
    expires_at             TIMESTAMPTZ                                       NOT NULL,
    CONSTRAINT pk_assessment_draft PRIMARY KEY (id),
    CONSTRAINT fk_assessment_draft_assessment FOREIGN KEY (assessment_uuid) REFERENCES assessment (uuid) ON DELETE CASCADE,
    CONSTRAINT fk_assessment_draft_owner FOREIGN KEY (owner_user_details_uuid) REFERENCES user_details (uuid),
    CONSTRAINT assessment_draft_base_aggregate_version_check CHECK (base_aggregate_version >= 0),
    CONSTRAINT assessment_draft_revision_check CHECK (revision >= 0),
    CONSTRAINT uq_assessment_draft_scope UNIQUE (assessment_uuid, owner_user_details_uuid, form_version, draft_key)
);

CREATE INDEX ix_assessment_draft_owner ON assessment_draft (assessment_uuid, owner_user_details_uuid);
CREATE INDEX ix_assessment_draft_expiry ON assessment_draft (expires_at);
