CREATE TABLE aggregate
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid            UUID UNIQUE                             NOT NULL,
    updated_at      TIMESTAMP                               NOT NULL,
    events_from     TIMESTAMP                               NOT NULL,
    events_to       TIMESTAMP                               NOT NULL,
    assessment_uuid UUID                                    NOT NULL,
    data            JSONB                                   NOT NULL,
    CONSTRAINT pk_aggregate PRIMARY KEY (id)
);

CREATE TABLE assessment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID UNIQUE                             NOT NULL,
    created_at TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_assessment PRIMARY KEY (id)
);

CREATE TABLE event
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid            UUID UNIQUE                             NOT NULL,
    created_at      TIMESTAMP                               NOT NULL,
    user_details    JSONB                                   NOT NULL,
    assessment_uuid UUID                                    NOT NULL,
    data            JSONB                                   NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

ALTER TABLE aggregate
    ADD CONSTRAINT FK_AGGREGATE_ON_ASSESSMENT_UUID FOREIGN KEY (assessment_uuid) REFERENCES assessment (uuid);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_ASSESSMENT_UUID FOREIGN KEY (assessment_uuid) REFERENCES assessment (uuid);
