CREATE TABLE user_details
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid         UUID UNIQUE                             NOT NULL,
    user_id      TEXT                                    NOT NULL,
    display_name TEXT                                    NOT NULL,
    auth_source  TEXT                                    NOT NULL,
    CONSTRAINT uq_user_id_and_type UNIQUE (user_id, auth_source)
);

CREATE TABLE assessment
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid            UUID UNIQUE                             NOT NULL,
    created_at      TIMESTAMPTZ                             NOT NULL,
    type            TEXT                                    NOT NULL,
    CONSTRAINT pk_assessment PRIMARY KEY (id)
);

CREATE INDEX ix_assessment_uuid ON assessment (uuid);

CREATE TABLE assessment_identifier
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid            UUID UNIQUE                             NOT NULL,
    created_at      TIMESTAMPTZ                             NOT NULL,
    identifier_type TEXT                                    NOT NULL,
    identifier      TEXT                                    NOT NULL,
    assessment_uuid UUID                                    NOT NULL,
    CONSTRAINT pk_assessment_identifier PRIMARY KEY (id),
    CONSTRAINT fk_assessment_identifier_assessment FOREIGN KEY (assessment_uuid) REFERENCES assessment (uuid) ON DELETE CASCADE
);

CREATE INDEX ix_assessment_identifier_type ON assessment_identifier (identifier_type);
CREATE INDEX ix_assessment_identifier_uuid ON assessment_identifier (uuid);

CREATE TABLE event
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY           NOT NULL,
    uuid              UUID UNIQUE                                       NOT NULL,
    created_at        TIMESTAMPTZ                                       NOT NULL,
    user_details      JSONB                                             NOT NULL,
    data              JSONB                                             NOT NULL,
    data_type         TEXT GENERATED ALWAYS AS (data ->> 'type') STORED NOT NULL,
    assessment_uuid   UUID                                              NOT NULL,
    user_details_uuid UUID                                              NOT NULL,
    parent_uuid       UUID                                              NULL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_event_assessment FOREIGN KEY (assessment_uuid) REFERENCES assessment (uuid) ON DELETE CASCADE,
    CONSTRAINT fk_event_user_details FOREIGN KEY (user_details_uuid) REFERENCES user_details (uuid),
    CONSTRAINT fk_event_parent FOREIGN KEY (parent_uuid) REFERENCES event (uuid) ON DELETE CASCADE
);

CREATE INDEX ix_event_assessment_uuid ON event (assessment_uuid);
CREATE INDEX idx_event_parent_uuid ON event (parent_uuid);

CREATE TABLE aggregate
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY           NOT NULL,
    uuid            UUID UNIQUE                                       NOT NULL,
    updated_at      TIMESTAMPTZ                                       NOT NULL,
    events_from     TIMESTAMPTZ                                       NOT NULL,
    events_to       TIMESTAMPTZ                                       NOT NULL,
    events_applied  BIGINT                                            NOT NULL,
    data            JSONB                                             NOT NULL,
    data_type       TEXT GENERATED ALWAYS AS (data ->> 'type') STORED NOT NULL,
    assessment_uuid UUID                                              NOT NULL,
    version         BIGINT                                            NOT NULL,
    CONSTRAINT pk_aggregate PRIMARY KEY (id),
    CONSTRAINT fk_aggregate_assessment FOREIGN KEY (assessment_uuid) REFERENCES assessment (uuid) ON DELETE CASCADE,
    CONSTRAINT aggregate_version_check CHECK (version >= 0)
);

CREATE INDEX ix_aggregate_state_assessment_uuid ON aggregate (assessment_uuid);

CREATE TABLE timeline
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID UNIQUE                             NOT NULL,
    created_at        TIMESTAMPTZ                             NOT NULL,
    event_type        TEXT                                    NOT NULL,
    data              JSONB                                   NOT NULL,
    custom_type       TEXT,
    custom_data       JSONB,
    user_details_uuid UUID                                    NOT NULL,
    assessment_uuid   UUID                                    NOT NULL,
    CONSTRAINT pk_timeline PRIMARY KEY (id),
    CONSTRAINT fk_timeline_assessment FOREIGN KEY (assessment_uuid) REFERENCES assessment (uuid) ON DELETE CASCADE,
    CONSTRAINT fk_timeline_user_details FOREIGN KEY (user_details_uuid) REFERENCES user_details (uuid) ON DELETE CASCADE
);
