CREATE TABLE user_details
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid         UUID UNIQUE                             NOT NULL,
    user_id      TEXT                                    NOT NULL,
    display_name TEXT                                    NOT NULL,
    auth_source  TEXT                                    NOT NULL,
    CONSTRAINT uq_user_id_and_type UNIQUE (user_id, auth_source)
);

INSERT INTO user_details (uuid, user_id, display_name, auth_source)
VALUES ('00000000-0000-0000-0000-000000000000', 'UNKNOWN_USER', 'Unknown User', 'NOT_SPECIFIED');


ALTER TABLE assessment
    ADD COLUMN user_details_uuid UUID NOT NULL DEFAULT ('00000000-0000-0000-0000-000000000000')
