CREATE TABLE user_details
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid         UUID UNIQUE                             NOT NULL,
    user_id      TEXT                                    NOT NULL,
    display_name TEXT                                    NOT NULL,
    auth_source  TEXT                                    NOT NULL,
    CONSTRAINT uq_user_id_and_type UNIQUE (user_id, auth_source)
);

INSERT INTO user_details (uuid, user_id, display_name, auth_source)
VALUES ('00000000-0000-0000-0000-000000000000', 'UNKNOWN_USER', 'Unknown User', 'NOT_SPECIFIED');

ALTER TABLE event
    ADD COLUMN user_details_uuid UUID NOT NULL DEFAULT ('00000000-0000-0000-0000-000000000000');

ALTER TABLE event
    DROP COLUMN user_details;

CREATE TABLE timeline
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID UNIQUE                             NOT NULL,
    created_at        TIMESTAMPTZ                             NOT NULL,
    event_type        TEXT                                    NOT NULL,
    data              JSONB                                   NOT NULL,
    custom_type       TEXT,
    custom_data       JSONB,
    user_details_uuid UUID                                    NOT NULL,
    assessment_uuid   UUID                                    NOT NULL,
    CONSTRAINT pk_timeline PRIMARY KEY (id),
    CONSTRAINT fk_timeline_assessment FOREIGN KEY (assessment_uuid) REFERENCES assessment (uuid) ON DELETE CASCADE,
    CONSTRAINT fk_timeline_user_details FOREIGN KEY (user_details_uuid) REFERENCES user_details (uuid) ON DELETE CASCADE
);
