CREATE TABLE oasys_version
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid            UUID UNIQUE                             NOT NULL,
    created_at      TIMESTAMPTZ                             NOT NULL,
    created_by      TEXT                                    NOT NUll,
    updated_at      TIMESTAMPTZ                             NOT NULL,
    version         BIGINT                                  NOT NULL,
    status          TEXT                                    NOT NULL,
    last_event      UUID                                    NOT NULL,
    assessment_uuid UUID                                    NOT NULL,
    CONSTRAINT pk_oasys_version PRIMARY KEY (id),
    CONSTRAINT fk_oasys_version_assessment FOREIGN KEY (assessment_uuid) REFERENCES assessment (uuid) ON DELETE CASCADE,
    CONSTRAINT fk_oasys_version_event FOREIGN KEY (last_event) REFERENCES event (uuid)
);
